### PR TITLE
Update to latest Kore.

### PR DESCRIPTION
**Pull request by luboslenco**

### CODE REVIEW

**Comment by RobDangerous** [comment]
Oh, I forgot about that issue...
We will have to get the patch_main function back, I have to put that into SPIRV-Cross somehow. Need that to get it to work reliably on D3D11/12. But will merge for now.

**Comment by luboslenco** [comment]
Oops, wondered what the patch_main was about.

**Comment by RobDangerous** [comment]
In D3D the control shader actually has two functions like that. Therefore krafix reguired the glsl shader to look like that too, for the actual glsl it put them back together, for D3D it used the functions as they are. SPIRV-Cross of course doesn't do that currently so I'll have to reimplement it.

**Comment by luboslenco** [comment]
I see, sounds reasonable!

**Pull request merged**
